### ISSUE TITLE
Grunion Contact form failures on jetpack.wp-a2z.org

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/bobbingwide#75]
While attempting to look at how the Grunion contact form works I had many problems viewing the Grunion contact form on jetpack.wp-a2z.org.  

For the field I got a Fatal on https://jetpack.wp-a2z.org/oik_shortcodes/contact-field/

<b>Fatal error</b>:  Uncaught TypeError: Cannot access offset of type string on string in /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2497
```
  | Stack trace:
  | #0 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/shortcodes.php(356): Grunion_Contact_Form::parse_contact_field('', '', 'contact-field')
  | #1 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik-css/includes/shortcodes-earlier.php(118): do_shortcode_tag(Array)
  | #2 [internal function]: do_shortcode_tag_earlier(Array)
  | #3 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik-css/includes/shortcodes-earlier.php(95): preg_replace_callback('/\\[(\\[?)(contac...', 'do_shortcode_ta...', '[contact-field]')
  | #4 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/class-wp-hook.php(307): do_shortcode_earlier('[contact-field]')
  | #5 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/plugin.php(191): WP_Hook-&gt;apply_filters('[contact-field]', Array)
  | #6 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik/libs/oik-sc-help.php(631): apply_filters('the_content', '[contact-field]')
  | #7 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik/libs/oik-sc-help.php(581): bw_expand_shortcode('[contact-field]')
  | #8 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik/libs/oik-sc-help.php(309): bw_invoke_shortcode('contact-field', NULL, 'oik generated e...')
  | #9 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik/libs/oik-sc-help.php(159): _sc__example('contact-field', NULL)
  | #10 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik-bwtrace/libs/bobbfunc.php(919): bw_lazy_sc_example('contact-field', NULL)
  | #11 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/class-wp-hook.php(307): bw_sc_example('contact-field')
  | #12 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters('', Array)
  | #13 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action(Array)
  | #14 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik/shortcodes/oik-codes.php(301): do_action('bw_sc_example', 'contact-field')
  | #15 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik/libs/oik-shortcodes.php(229): bw_code(Array, '', 'bw_code')
  | #16 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/shortcodes.php(356): bw_shortcode_event(Array, '', 'bw_code')
  | #17 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik-css/includes/shortcodes-earlier.php(118): do_shortcode_tag(Array)
  | #18 [internal function]: do_shortcode_tag_earlier(Array)
  | #19 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/oik-css/includes/shortcodes-earlier.php(95): preg_replace_callback('/\\[(\\[?)(bw_cod...', 'do_shortcode_ta...', 'Display Grunion...')
  | #20 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/class-wp-hook.php(307): do_shortcode_earlier('Display Grunion...')
  | #21 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/plugin.php(191): WP_Hook-&gt;apply_filters('Display Grunion...', Array)
  | #22 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/post-template.php(253): apply_filters('the_content', 'Display Grunion...')
  | #23 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/themes/genesis/lib/structure/post.php(486): the_content()
  | #24 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/class-wp-hook.php(307): genesis_do_post_content('')
  | #25 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters(NULL, Array)
  | #26 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action(Array)
  | #27 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/themes/genesis/lib/structure/loops.php(119): do_action('genesis_entry_c...')
  | #28 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/themes/genesis/lib/structure/loops.php(38): genesis_standard_loop()
  | #29 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/class-wp-hook.php(307): genesis_do_loop('')
  | #30 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/class-wp-hook.php(331): WP_Hook-&gt;apply_filters('', Array)
  | #31 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/plugin.php(476): WP_Hook-&gt;do_action(Array)
  | #32 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/themes/genesis/lib/framework.php(66): do_action('genesis_loop')
  | #33 /home/customer/www/bobbingwide.org.uk/public_html/wp-content/themes/genesis-a2z/single-oik_shortcodes.php(55): genesis()
  | #34 /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/template-loader.php(106): include('/home/customer/...')
  | #35 /home/customer/www/bobbingwide.org.uk/public_html/wp-blog-header.php(19): require_once('/home/customer/...')
  | #36 /home/customer/www/bobbingwide.org.uk/public_html/index.php(17): require('/home/customer/...')
  | #37 {main}
  | thrown in <b>/home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/jetpack/modules/contact-form/grunion-contact-form.php</b> on line <b>2497</b><br />
```

For the form I got 

Warning: Attempt to read property "user_email" on bool in /home/customer/www/bobbingwide.org.uk/public_html/wp-content/plugins/jetpack/modules/contact-form/grunion-contact-form.php on line 2001

**Comment by bobbingwide** [comment]
Problem also occurs in development with Jetpack 11.2. 
It's probably the fact that the `[contact-field]` shortcode no longer works unless it's part of the `[contact-form]`

**Comment by bobbingwide** [comment]
### Workaround

Fixed by not allowing the `contact-field` shortcode to be generated automatically.
```
<!-- wp:paragraph -->
<p>Display Grunion Contact field in a Grunion contact form. </p>
<!-- /wp:paragraph -->

<!-- wp:oik-css/geshi {"lang":"html","text":"Example Telephone field. ","content":"[contact-form]\n[contact-field label=Telephone type=telephone required=true ]\n[/contact-form]"} /-->

<!-- wp:paragraph -->
<p>[contact-form][contact-field label=Telephone type=telephone required=true ] [/contact-form]</p>
<!-- /wp:paragraph -->
```

**Comment by bobbingwide** [comment]
> For the form I got Warning: Attempt to read property "user_email" on bool

This still happens with the latest version of the code. Line number is 2445 now.

**Comment by bobbingwide** [comment]
I'm not going to bother to attempt to fix any code. The workaround is sufficient at present.
