### ISSUE TITLE
Attempt to create a Headless WordPress installation using Local and Atlas 

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/bobbingwide#82]
For the November Online WordPress Portsmouth Meetup I want someone to be able to talk fairly knowledgeably about Headless WordPress and to be able to demonstrate one or more actual installations.  

There are multiple commercial solutions available for WordPress. One of those is Atlas by WPEngine. You can sign up to use Altas for free for 4 months. I believe you're expected to be able to use **local** to install a headless WordPress solution.

I've created this issue to record my progress. 
- - - 
It didn't start well. 

1. My local installation doesn't appear to work.
2. I couldn't understand the terms of service. 
3. I've no idea whether or not I'll be charged for a solution I'm not using in 4 months time
4. My attempts to install a headless solution in local failed
5.  I also tried to Create app from https://my.wpengine.com/atlas#/ but that also failed the first time.

For each of the above I had no idea why I was doing what I was being asked to do. 
So I was just hitting buttons in the vain hope that I might eventually understand something.
- - -
The previous section was written a couple of weeks ago. I've made a reasonable amount of progress.
I now have several installations in my local development environment(s) and one on my Atlas Sandbox.

**Comment by bobbingwide** [comment]
> 1. My local installation doesn't appear to work.
It does now. I managed to create an installation called Gatsby. WordPress and WP-CLI run with some Warnings. 

```
WP-CLI: Warning: Version warning: Imagick was compiled against ImageMagick version 1799 but version 1808 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
WP-CLI: WP-CLI 2.6.0
Composer: Warning: Version warning: Imagick was compiled against ImageMagick version 1799 but version 1808 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Composer: Warning: Version warning: Imagick was compiled against ImageMagick version 1799 but version 1808 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Composer: Composer version 2.1.5 2021-07-23 10:35:47
PHP: Warning: Version warning: Imagick was compiled against ImageMagick version 1799 but version 1808 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
PHP: 7.4.1
MySQL: mysql  Ver 8.0.16 for Win64 on x86_64 (MySQL Community Server - GPL)
----
Loaded Shell for Local Site: gatsby
```

**Comment by bobbingwide** [comment]
> 2. I couldn't understand the terms of service.

I gave up trying to understand the second paragraph in the first clause. 1. Agreement a. 

That agreement between us is comprised of these Terms of Service, the Order to which they are attached or by which they are referenced, the SLA, AUP, DPA, and Privacy Policy which are referenced herein, and any other terms, exhibits, schedules, or addenda which are referenced by any of the preceding (collectively the “Agreement”).

I know what an SLA is but not AUP or DPA. ... seems I need to read 13. Definitions 

1 b. is just as bad as 1 a.

When time comes to cancel I'll have to visit https://my.wpengine.com/my_account/cancel

**Comment by bobbingwide** [comment]
> 3. I've no idea whether or not I'll be charged for a solution I'm not using in 4 months time

**Comment by bobbingwide** [comment]
> 4. My attempts to install a headless solution in local failed

But I did manage to create one called blue something ( tbc ) 
front end: https://hd35phgxakkpod7dflh81yfya.js.wpenginepowered.com/

and today I managed to create a site in local called gatsby while following
https://europe.wordcamp.org/2022/session/build-gatsby-wordpress-sites-with-gatsby-wp-themes/

**Comment by bobbingwide** [comment]
5. I also tried to Create app from https://my.wpengine.com/atlas#/ but that also failed the first time.

I now have access to Atlas and have created a blueprint site. See above. I've received instructions from wpengine with a list of tutorials for Local/Atlas, Faust and WPGraphQL



WP Engine Logo Image

 

Hi Herb, 

 

Now that you have access to Atlas, and have spun up an Atlas Blueprint, we would like to guide you on how you can customize and extend your project.

 
Below you will find a list of tutorials for the most popular tools in the Atlas ecosystem!

Local – local development platform for WordPress

Site: 

    Local
    Atlas add-on for Local

Local/Atlas Tutorial: 

    Using the Atlas: Headless WP Add-on (written)
    How to use the Atlas Headless WP Add-on in Local (video)

  	  	 

Faust.js – front-end framework for headless WordPress

Site: 

    Faust.js

Tutorial: 

    Faust.js Tutorial for PHP Developers (written)
    Faust.js Tutorial Walk-Through (video)
    Setting Up Post and Page Previews (written)

  	  	 

WPGraphQL – GraphQL API for WordPress

Site: 

    GraphQL API for WordPress (WPGraphQL)

Tutorial: 

    Intro to GraphQL (written) 

  	  	 

Atlas Content Modeler – Custom post types and fields for headless WordPress

Site: 

    Atlas Content Modeler

Tutorial: 

    How to use Atlas Content Modeler (written)
    ACM - Real App Walk-Through (video)
    Faust.js & ACM - Interacting with Custom Post Types (written)

If you have a question, get stuck, or want to share what you've built, join us in the Headless WordPress Discord server.

**Comment by bobbingwide** [comment]
- I've installed the Atlas addon to my instance of local
- and created a new site called local-atlas, WordPress userid: atlas
- Visit http://localhost:10011 and it's  a basic install with Twenty Twenty Two

**Comment by bobbingwide** [comment]
This worked. I then edited the first post Hello World and added two more.
If you scroll down the home page you can see these posts.
![image](https://user-images.githubusercontent.com/2474435/197862108-a21a21ef-de24-41c6-bcd3-f59cdae65aea.png)

**Comment by bobbingwide** [comment]
Having got the front end to connect to the atlas local backend I then attempted to change it to connect to `s.b/cwiccer`.

I changed `.env.local` to
```
NEXT_PUBLIC_WORDPRESS_URL=https://s.b/cwiccer
FAUSTWP_SECRET_KEY=d5f2d0e7-2684-453c-b86c-e2788b9664a3
```

But this produced
```
[GQtyError: request to https://s.b/cwiccer/graphql failed, reason: unable to verify the first certificate] {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

**Comment by bobbingwide** [comment]
Now I want to create my own front end for `s.b/cwiccer`.

**Comment by bobbingwide** [comment]
In oik-bwtrace, when we want to see the REST request we an access global $HTTP_RAW_POST_DATA;
The REST API populates this using $HTTP_RAW_POST_DATA = file_get_contents( 'php://input' );
GraphQL does something similar in static method `Router::get_raw_data()`

**Comment by bobbingwide** [comment]
Having got the local installation in `faust` to connect to s.b/cwiccer I then tried with a clone of  https://github.com/bobbingwide/atlas-blueprint-blog in `atlas-blueprint-blog`

I encountered a number of problems getting the system to build and connect successfully.
1. Several GQtyError messages

```
[GQtyError: Cannot query field "testimonials" on type "RootQuery".] {
  graphQLErrors: [
    {
      message: 'Cannot query field "testimonials" on type "RootQuery".',
      extensions: [Object],
      locations: [Array]
    }
  ]
}
```

2. No posts being returned for `categoryName: uncategorized`... even though I'd changed the `slug` for the faust installation
3. Images not being loaded to 
```
error - FetchError: request to https://s.b/cwiccer/wp-content/uploads/2021/10/oik-libs-banner-772x250-1.png failed, reason: self signed certificate
    at ClientRequest.<anonymous> (C:\apache\htdocs\atlas-blueprint-blog\node_modules\next\dist\compiled\node-fetch\index.js:1:65756)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
```

which I resolved by adding this line in faust.config.js
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

but this causes this message in the log
```
event - compiled client and server successfully in 873 ms (894 modules)
(node:25468) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by bobbingwide** [comment]
But I'm generally confused about the URLs and how the JS code constructs them. 
content | URL
-------- | -----------
home page | http://localhost:3000/
single page | prefixed with `cwiccer` eg http://localhost:3000/cwiccer/contact-us
single post  | prefixed with `posts` eg http://localhost:3000/posts/image-block-caption-link-clicking
category archive | prefixed with `category` eg http://localhost:3000/category/gutenberg

But at least something is working
![image](https://user-images.githubusercontent.com/2474435/200415957-727e4a58-381b-455f-9f95-fdb5f59c7185.png)

and, amazingly, when I stopped the build for atlas-blueprint-blog and replaced it with the build for faust
the content in the browser was reloaded.
```
C:\apache\htdocs\atlas-blueprint-blog>cd ..\faust

C:\apache\htdocs\faust>npm run dev

> @faustjs/next-headless-getting-started@0.1.0 dev C:\apache\htdocs\faust
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\apache\htdocs\faust\.env.local
event - compiled client and server successfully in 1902 ms (601 modules)
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 690 ms (686 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling / (client and server)...
event - compiled client and server successfully in 480 ms (694 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling /posts/[postSlug] (client and server)...
event - compiled client and server successfully in 429 ms (697 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
```
so it looked like the first screen capture https://github.com/bobbingwide/bobbingwide/issues/82#issuecomment-1292563960

**Comment by bobbingwide** [comment]
Presentation and recording of Zoom meeting now published. See https://www.wp-pompey.org.uk/meetup/wordpress-portsmouth-online-meetup-16th-november-2022-headless-wordpress-101/
