### ISSUE TITLE
Attempt to create a Headless WordPress environment using GatsbyWPThemes

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/bobbingwide#83]
At WP-Pompey on 16th November I intend to talk about Headless WordPress solutions.
One of the options is to use Gatsby and Gatsby Themes

### Requirements
- Create a headless WordPress environment using Gatsby WP Themes.

### Proposed solution

- Follow the WCEU workshop

https://europe.wordcamp.org/2022/session/build-gatsby-wordpress-sites-with-gatsby-wp-themes/

- and the guide at 

https://doc.gatsbywpthemes.com/setup/install

**Comment by bobbingwide** [comment]
OK, so I've created the WordPress site called `gatsby` within _local_. `C:\Users\herb\Local Sites\gatsby\app\public`

Now I need to install the Gatsby Starter. 
I'm going to do this in `c:\apache\htdocs\gatsby`

**Comment by bobbingwide** [comment]
C:\apache\htdocs\gatsby>npm -i g corepack
undefined

C:\apache\htdocs\gatsby>npm i -g corepack
C:\Users\herb\AppData\Roaming\npm\pnpm -> C:\Users\herb\AppData\Roaming\npm\node_modules\corepack\dist\pnpm.js
C:\Users\herb\AppData\Roaming\npm\pnpx -> C:\Users\herb\AppData\Roaming\npm\node_modules\corepack\dist\pnpx.js
C:\Users\herb\AppData\Roaming\npm\yarn -> C:\Users\herb\AppData\Roaming\npm\node_modules\corepack\dist\yarn.js
C:\Users\herb\AppData\Roaming\npm\yarnpkg -> C:\Users\herb\AppData\Roaming\npm\node_modules\corepack\dist\yarnpkg.js
C:\Users\herb\AppData\Roaming\npm\corepack -> C:\Users\herb\AppData\Roaming\npm\node_modules\corepack\dist\corepack.js
+ corepack@0.14.2

**Comment by bobbingwide** [comment]
Preparing for running `gatsby develop`.

There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run "npm install"? You might need to delete your "package-lock.json" as well.

C:\apache\htdocs\gatsby>npm install
Error: Failed to replace env in config: ${GWPT_AUTH_TOKEN}
    at C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:411:12)
    at parseField (C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:389:7)
    at C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:328:23)
    at ConfigChain.addString (C:\Users\herb\AppData\Roaming\npm\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:316:10)
    at C:\Users\herb\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:115:16
C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\npm.js:59:13)
    at process.errorHandler (C:\Users\herb\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:205:32)
    at process.emit (events.js:400:28)
    at process._fatalException (internal/process/execution.js:167:25)

C:\apache\htdocs\gatsby>set GWPT_AUTH_TOKEN=the-token-in-the-welcome-to-gatsbyWPThemes-email

C:\apache\htdocs\gatsby>npm install
[ .................] | fetchMetadata: sill install loadAllDepsIntoIdealTree

**Comment by bobbingwide** [comment]
![image](https://user-images.githubusercontent.com/2474435/197609973-57bad9ea-3908-4cd2-abf1-f33193f08de0.png)

This is a known problem. https://github.com/medikoo/es5-ext/issues/186

**Comment by bobbingwide** [comment]
C:\apache\htdocs\gatsby>gatsby develop
success compile gatsby files - 22.750s
success load gatsby config - 0.334s
success load plugins - 10.443s
warn gatsby-plugin-react-helmet: Gatsby now has built-in support for modifying the document head. Learn more at https://gatsby.dev/gatsby-head
success onPreInit - 0.031s
success initialize cache - 2.438s
success copy gatsby files - 0.814s
warn DefinePlugin
Conflicting values for 'process.env.NODE_ENV'
success Compiling Gatsby Functions - 3.990s

 ERROR #11321  PLUGIN

"gatsby-plugin-webfonts" threw an error while running the onPreBootstrap lifecycle:

PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users



  Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
  Migration guide for end-users:
  https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

  - processor.es6:139 Processor.normalize
    [gatsby]/[postcss]/lib/processor.es6:139:15

  - processor.es6:38 new Processor
    [gatsby]/[postcss]/lib/processor.es6:38:25

  - postcss.es6:34 postcss
    [gatsby]/[postcss]/lib/postcss.es6:34:10

  - index.js:167 cssnanoPlugin
    [gatsby]/[cssnano]/src/index.js:167:10

  - web-fonts.js:46 _callee$
    [gatsby]/[gatsby-plugin-webfonts]/web-fonts.js:46:77

  - regeneratorRuntime.js:72 tryCatch
    [gatsby]/[@babel]/runtime/helpers/regeneratorRuntime.js:72:17

  - regeneratorRuntime.js:55 Generator._invoke
    [gatsby]/[@babel]/runtime/helpers/regeneratorRuntime.js:55:24

  - regeneratorRuntime.js:97 Generator.next
    [gatsby]/[@babel]/runtime/helpers/regeneratorRuntime.js:97:21

  - new Promise

  - web-fonts.js:68 merge
    [gatsby]/[gatsby-plugin-webfonts]/web-fonts.js:68:29

  - web-fonts.js:80 _callee2$
    [gatsby]/[gatsby-plugin-webfonts]/web-fonts.js:80:20

  - regeneratorRuntime.js:72 tryCatch
    [gatsby]/[@babel]/runtime/helpers/regeneratorRuntime.js:72:17


success onPreBootstrap - 8.399s

 ERROR #gatsby-source-wordpress_111002

 gatsby-source-wordpress  Error: Request failed with status code 400
    at createError (C:\apache\htdocs\gatsby\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\apache\htdocs\gatsby\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\apache\htdocs\gatsby\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

GraphQL request to undefined/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed and active in your WordPress backend
  - Your WordPress debug.log does not contain critical errors

not finished createSchemaCustomization - 0.172s
not finished  gatsby-source-wordpress  ensuring plugin requirements are met - 0.154s

**Comment by bobbingwide** [comment]
I renamed `.env-sample` and edited `.env` to set the GATSBY_ env vars.
Next run I got
C:\apache\htdocs\gatsby>gatsby develop
success compile gatsby files - 31.234s
success load gatsby config - 0.146s
success load plugins - 3.391s
warn gatsby-plugin-react-helmet: Gatsby now has built-in support for modifying the document head. Learn more at https://gatsby.dev/gatsby-head
success onPreInit - 0.019s
success initialize cache - 0.196s
success copy gatsby files - 0.644s
warn DefinePlugin
Conflicting values for 'process.env.NODE_ENV'
success Compiling Gatsby Functions - 0.824s

 ERROR #11321  PLUGIN

"gatsby-plugin-webfonts" threw an error while running the onPreBootstrap lifecycle:

PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users



  Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
  Migration guide for end-users:
  https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

**Comment by bobbingwide** [comment]
Re-reading the instructions it looks like I should be using yarn to install the node modules not npm.
I tried that but it failed

C:\apache\htdocs\gatsby>yarn install
➤ YN0000: ┌ Resolution step
➤ YN0032: │ sharp@npm:0.30.7: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:5.0.0: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0032: │ lmdb@npm:2.5.3: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:4.3.0: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ msgpackr-extract@npm:2.1.2: Implicit dependencies on node-gyp are discouraged
➤ YN0035: │ @gatsbywpthemes/gatsby-plugin-gwpt-packages-light@npm:^1.1.5: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@gatsbywpthemes%2fgatsby-plugin-gwpt-packages-light
➤ YN0000: └ Completed in 7s 548ms
➤ YN0000: Failed with errors in 7s 559ms
➤ YN0061: async-cache@npm:1.1.0 is deprecated: No longer maintained. Use [lru-cache](http://npm.im/lru-cache) version 7.6 or higher, and provide an asynchronous `fetchMethod` option.
➤ YN0032: lmdb@npm:2.5.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: @parcel/watcher@npm:2.0.5: Implicit dependencies on node-gyp are discouraged
➤ YN0032: node-addon-api@npm:3.2.1: Implicit dependencies on node-gyp are discouraged

**Comment by bobbingwide** [comment]
I gave up with this. Presentation and Zoom recording now published https://www.wp-pompey.org.uk/meetup/wordpress-portsmouth-online-meetup-16th-november-2022-headless-wordpress-101/
