### ISSUE TITLE
Attempt to create multiple headless solutions for the same local site ( s.b/cwiccer -> now cwiccer.local)

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/bobbingwide#89]
I've raised multiple issues prefixed _Attempt to create a Headless WordPress install using_ ...
This issue is an extension of #82, to create multiple headless solutions associated with the same local install - `s.b/cwiccer` 

In #82
- I started with an Atlas Sandbox on WP Engine's hosting 
- then installed the same solution in _local_ using the Atlas addon ( local site is atlas local )
- installed the required WordPress plugins on s.b/cwiccer
- then connected it up 
- See https://github.com/bobbingwide/bobbingwide/issues/82#issuecomment-1292563960

Next I cloned the front end logic from `C:\Users\herb\Local Sites\atlas-local\app-node` into `c:\apache\htdocs\faust`.
Note: The Git repo was created using Create Next App... but I'm not sure what the build command was
but I believe the source code is from wpengine/faustjs

- I built the code ( localhost:3000)  and connected it to s.b/cwiccer
- Yesterday, I cloned https://github.com/bobbingwide/atlas-blueprint-blog into my local development environment as atlas-blueprint-blog and built that too
- After some fiddling I got that to work as well https://github.com/bobbingwide/bobbingwide/issues/82#issuecomment-1306169634

### The requirement for this PR is:

- create multiple headless solutions for the same local site
- With the same WordPress content
- and the same URL structure being used by both faust and atlas-blueprint-blog.
- Solutions should be able to run concurrently

ie. Understand how to change the atlas-blueprint-blog code to work the same as faust https://github.com/bobbingwide/bobbingwide/issues/82#issuecomment-1306199548

**Comment by bobbingwide** [comment]
Headless dir | Run as
----------- | -------------
atlas-blueprint-blog | http://localhost:3000
faust | http://localhost:4000

Note: In `s.b/cwiccer`'s Faust settings the Front-end site URL is `http://localhost:3000` 
when I click on the **Visit Site** link I get a 404 for the URL  `http://localhost:3000/cwiccer`

If I change this to `http://localhost:4000` I get a similar problem with the Faust front end.

**Comment by bobbingwide** [comment]
I concluded that the logic doesn't fully support subdirectory installs. 
To fix this I created a new local domain called `cwiccer.local`
Attempting to access the site using http: led to warnings of an insecure site, that didn't happen when the site was called localhost.
I also got these messages running `npm run dev`.

```
[GQtyError: invalid json response body at http://s.b/cwiccer/graphql reason: Unexpected token < in JSON at position 0] {
  type: 'invalid-json'
}
```

I assumed this was because I'd forgotten to change `NEXT_PUBLIC_WORDPRESS_URL` in `.env.local`.

**Comment by bobbingwide** [comment]
> Attempting to access the site using http: led to warnings of an insecure site, that didn't happen when the site was called localhost.

I set up the SSL certificate for cwiccer.local under the certificate for s.b

**Comment by bobbingwide** [comment]
The reason that altas-blueprint-blog's links to posts aren't correct is because I didn't uses a custom permalink structure of `/posts/%postname%/`

Changing this permalink resolves the issue for atlas-blueprint-blog for single post, and also works for faust.
But it breaks the category archive URL. The Category base needs to be set to `category`.

**Comment by bobbingwide** [comment]
One further requirement - try generating a static site using wp2static

**Comment by bobbingwide** [comment]
Another requirement.... generate another headless front end using the latest faustjs.
See https://faustjs.org/docs/getting-started

```
C:\apache\htdocs>npx create-next-app -e https://github.com/wpengine/faustjs/tree/main --example-path examples/next/faustwp-getting-started --use-npm
npx: installed 1 in 1.988s
√ What is your project named? ... faustjs
Creating a new Next.js app in C:\apache\htdocs\faustjs.

Downloading files from repo https://github.com/wpengine/faustjs/tree/main. This might take a moment.

Installing packages. This might take a couple of minutes.

[ .................] - fetchMetadata: sill pacote range manifest for @emotion/css@^11.7.1 fetched in 163ms
```

**Comment by bobbingwide** [comment]
When I ran `npm run dev` for faustjs I got an error. I reported this on Discord
```
@faustwp/getting-started-example@0.1.0 dev C:\apache\htdocs\faustjs
faust dev

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn next ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn next',
  path: 'next',
  spawnargs: [ 'dev' ]
}
```
changing the command to run `next dev` instead of `faust dev` allowed me to proceed.

**Comment by bobbingwide** [comment]
I did a clean install and tried again
```
C:\apache\htdocs\faustjs>npm clean-install
npm WARN prepare removing existing node_modules/ before installation
added 343 packages in 67.83s

C:\apache\htdocs\faustjs>npm run dev

> @faustwp/getting-started-example@0.1.0 dev C:\apache\htdocs\faustjs
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\apache\htdocs\faustjs\.env.local
event - compiled client and server successfully in 16.1s (800 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 1048 ms (801 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling /[...wordpressNode] (client and server)...
event - compiled client and server successfully in 345 ms (804 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
possible templates:  [ 'page-about-2', 'page-1673', 'page', 'singular', 'index' ]
possible templates:  [ 'page-about-2', 'page-1673', 'page', 'singular', 'index' ]
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling / (client and server)...
event - compiled client and server successfully in 279 ms (807 modules)
possible templates:  [ 'front-page', 'page-home', 'page-3886', 'page', 'singular', 'index' ]
possible templates:  [ 'front-page', 'page-home', 'page-3886', 'page', 'singular', 'index' ]
```

**Comment by bobbingwide** [comment]
In cwiccer.local I've set up my permalinks such that Home is the front page and Blog is the posts page. When I visit Blog I get a 404. I don't know why.

**Comment by bobbingwide** [comment]
Shortcodes such as `[cwiccer]` deliver CSS to the browser. This information is not returned on the GraphQL query to the output isn't styled.

**Comment by bobbingwide** [comment]
When I remove a menu item from the Primary menu it slips to the end of the menu displayed in the front end.
The menu doesn't display all the items in the primary menu.

**Comment by bobbingwide** [comment]
Image with src "https://cwiccer.local/wp-content/uploads/2021/10/oik-libs-banner-772x250-1.png" and "layout='fill'" has unused properties assigned. Please remove "width" and "height".
(node:14880) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

**Comment by bobbingwide** [comment]
I tried again with a fresh install
```
C:\apache\htdocs>npx create-next-app -e https://github.com/wpengine/faustjs/tree/main --example-path examples/next/faustwp-getting-started --use-npm
npx: installed 1 in 2.519s
√ What is your project named? ... johann
Creating a new Next.js app in C:\apache\htdocs\johann.

Downloading files from repo https://github.com/wpengine/faustjs/tree/main. This might take a moment.

Installing packages. This might take a couple of minutes.

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm64@12.3.3 (node_modules\next\node_modules\@next\swc-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm64@12.3.3: wanted {"os":"android","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm-eabi@12.3.3 (node_modules\next\node_modules\@next\swc-android-arm-eabi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm-eabi@12.3.3: wanted {"os":"android","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@12.3.3 (node_modules\next\node_modules\@next\swc-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@12.3.3: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-freebsd-x64@12.3.3 (node_modules\next\node_modules\@next\swc-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-freebsd-x64@12.3.3: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@12.3.3 (node_modules\next\node_modules\@next\swc-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@12.3.3: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-musl@12.3.3 (node_modules\next\node_modules\@next\swc-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-musl@12.3.3: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-gnu@12.3.3 (node_modules\next\node_modules\@next\swc-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-gnu@12.3.3: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm-gnueabihf@12.3.3 (node_modules\next\node_modules\@next\swc-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm-gnueabihf@12.3.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-gnu@12.3.3 (node_modules\next\node_modules\@next\swc-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-gnu@12.3.3: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@12.3.3 (node_modules\next\node_modules\@next\swc-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@12.3.3: wanted {"os":"win32","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-musl@12.3.3 (node_modules\next\node_modules\@next\swc-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-musl@12.3.3: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-ia32-msvc@12.3.3 (node_modules\next\node_modules\@next\swc-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-ia32-msvc@12.3.3: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-autosize-textarea@7.1.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-autosize-textarea@7.1.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @emotion/babel-plugin@11.10.5 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-jsx@7.18.6 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.

added 330 packages from 235 contributors and audited 346 packages in 70.962s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Initialized a git repository.

Success! Created johann at C:\apache\htdocs\johann
Inside that directory, you can run several commands:

  npm run dev
    Starts the development server.

  npm run build
    Builds the app for production.

  npm start
    Runs the built app in production mode.

We suggest that you begin by typing:

  cd johann
  npm run dev

```

**Comment by bobbingwide** [comment]
C:\apache\htdocs\johann>npm run dev

> @faustwp/getting-started-example@0.1.0 dev C:\apache\htdocs\johann
> faust dev

Faust - error - Could not find NEXT_PUBLIC_WORDPRESS_URL environment variable.

**Comment by bobbingwide** [comment]
```
C:\apache\htdocs\johann>copy .env.local.sample .env.local
        1 file(s) copied.

C:\apache\htdocs\johann>more .env.local
# Your WordPress site URL
NEXT_PUBLIC_WORDPRESS_URL=https://faustexample.wpengine.com

# Plugin secret found in WordPress Settings->Headless
# FAUSTWP_SECRET_KEY=YOUR_PLUGIN_SECRET

C:\apache\htdocs\johann>npm run dev

> @faustwp/getting-started-example@0.1.0 dev C:\apache\htdocs\johann
> faust dev

Faust - warn - Could not find FAUSTWP_SECRET_KEY environment variable.
Faust - warn - Some functionality may be limited.
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn next ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn next',
  path: 'next',
  spawnargs: [ 'dev' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @faustwp/getting-started-example@0.1.0 dev: `faust dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @faustwp/getting-started-example@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\herb\AppData\Roaming\npm-cache\_logs\2022-11-11T12_05_23_126Z-debug.log
```

**Comment by bobbingwide** [comment]
I managed to get the code to run by changing the shell( 'next' ) command in @faustwp/cli.
 
I've raised an issue. https://github.com/wpengine/faustjs/issues/1144

I'm not sure whether or not faust and next need to be installed globally in order for this code to work.
I'm loathe to uninstall them.

**Comment by bobbingwide** [comment]
> Shortcodes such as [cwiccer] deliver CSS to the browser. This information is not returned on the GraphQL query. The output isn't styled.

![image](https://user-images.githubusercontent.com/2474435/201395497-71d4130b-43ff-4e48-af13-1516da526ba4.png)


A quick and dirty hack is to always enqueue the `cwiccer.css` copied from the plugin into the _tailless theme_. 
![image](https://user-images.githubusercontent.com/2474435/201395140-461185ce-374a-4e04-87d2-c4fa035dedb4.png)

**Comment by bobbingwide** [comment]
Presentation and Zoom recording now published. See https://www.wp-pompey.org.uk/meetup/wordpress-portsmouth-online-meetup-16th-november-2022-headless-wordpress-101/
